package eu.throup.advent2020.day5

import org.scalatest.freespec.AnyFreeSpec

class day5Spec extends AnyFreeSpec {
  "day 5 - part 1" - {
    "define the api" - {
      "takes a single string as input" in {
        part1(example1Input)
      }
      "returns an Int as output" in {
        val output: Int = part1(example1Input)
      }
    }

    "examples" - {
      "Instruction example" in {
        val input = example1Input
        val output = part1(input)

        assert(output == 820)
      }

      "Task set" in {
        val input = challengeInput
        val output = part1(input)

        assert(output == 908)
      }
    }
  }

  "day 5 - part 2" - {
    "define the api" - {
      "takes a single string as input" in {
        part2(example2Input)
      }
      "returns an Int as output" in {
        val output: Int = part2(example2Input)
      }
    }

    "examples" - {
      "Instruction example" in {
        val input = example2Input
        val output = part2(input)

        assert(output == 28)
      }

      "Task set" in {
        val input = challengeInput
        val output = part2(input)

        assert(output == 619)
      }
    }
  }
  val example1Input = "FBFBBFFRLR\nBBFFBBFRLL\nBFFFBBFRRR\nFFFBBBFRRR"

  val example2Input = "FFFFFBBLLL\nFFFFFBBLLR\nFFFFFBBLRL\nFFFFFBBLRR\nFFFFFBBRLR\nFFFFFBBRRL\nFFFFFBBRRR"

  val challengeInput = "BBFBBBBRRL\nFBFFFFBLRL\nFBFBBFFRLR\nFBFFFBFRLR\nFFBBFFFLRR\nFFBBBFFRRR\nBFBBFBFLRL\nBFFFBFFLRR\nFBBBFFBLLR\nBBFFBBFRRL\nBFBBBBBRLR\nFBBBBFFLLR\nFFBFFFBLLR\nFFBBFBFRRR\nBBFBFFFRRR\nFFBFFBBLLR\nFBBFFBBLRL\nFFBBBFBLLL\nFFBFFBBLRR\nFBFFBFBLLR\nFFFBBBFLLL\nBFBBFBFRLR\nBBFBBBFLLL\nFBBBFBBRLL\nFFBBBBFRRL\nBFBBBBFLRR\nBBFBBFBLRL\nFFBFFFBLRL\nBFBBBBBRRR\nFFFBFBFLLR\nBFBFBBBLLR\nFFBFBBBLRL\nFFFBFBBLRR\nBFFBFFFLLL\nBFFFBFBLRL\nBFBFFFBRLL\nBBFFFFBRLR\nFBBFFFBLRR\nBFFFFBFLLL\nBBBFFFFLLL\nBFBFFBBRLL\nBBFBFFFRRL\nBFBBFFFRLR\nBBFBFBFRRL\nFBBFFBFRRL\nBFBFBFFRRL\nFFBFFFFLLR\nFBBBFBBLLR\nBBFFBFBRLL\nBFFBFBBRLL\nFBBFFFFRRR\nBFFFBBBLRL\nFFBBFFBLLL\nFFFBBFFRRL\nFBFBBBBLRR\nFFBBBFFLLL\nFBFBFFBRRR\nFBBFFBBLLR\nFBFFBFFRLL\nBFBBBFFRLR\nFBFFBBBLRR\nFBFFFFBRLR\nBBFFBBFLRL\nFBFFBBFLRL\nFBFBBFFRRR\nBFBBBFBLRL\nFBFBFFFLLR\nFFFFBBBLLR\nBFBFFBBLLR\nBFFBBBFRLR\nBFBBBFFLRR\nBBFFFBBLLR\nBFFFBBFLRL\nFBFFBFBLRL\nFBBBFFFRRL\nFBFFFFBLLL\nBFBFFBBRLR\nBFBFBBBLRL\nBFFBFBBRLR\nFBBFBBBLLR\nFFBFBFFRLL\nFFFBBBBLRR\nBFBFFFFLLL\nBBFBFBBLLR\nBFFFBBBRLR\nFFBFFBFRLR\nFBBFBBBLRL\nBBFFFBBLLL\nFFBFFBBRRR\nFBBBBFBLLR\nBBFBBFFRLL\nBFBBBBFRLR\nBBFBFFBRLR\nFFBFFFFLLL\nBBFBFBFRLL\nFFBFFBBRLL\nFBBFFFFRLR\nFFBBBBBRRR\nBBFFBBBLRL\nBFFBBFBRLL\nBFFFBBFRLL\nBFFBFBFLRL\nFBFFFFFRRR\nBFFBFBBRRL\nFBFBBBFLLR\nFBFBFBBRLL\nBBBFFFFRRR\nBFBFBFFLRL\nFFFFBFBRLL\nFFBBFFBLRL\nBBFFBFBLLL\nBFFBBBBRLL\nBFFBBBBRRR\nBFBBBBFRRL\nBBBFFFBLRL\nFFBBFFFRRR\nBFFFFFBRLR\nFFFBBFBLLL\nBFBFBBFRLR\nFBBBFBFLRL\nBFBFBFFRLR\nBBFBBFFLRL\nBFFFBFBLLL\nBFFFFBBRLL\nFFBFFFFRRL\nBFFBFBBLLR\nFFFFBBBLLL\nFBBFFBBRRL\nBFBFFFFLLR\nFBFBFBFRLL\nFBBBBBBLRR\nBBFFFFBLRR\nFFFFBFBRRR\nFBBBBFBRLL\nBBFBFBBLRR\nFFBBFBFLLL\nBFBBFFBLRL\nFFFBBBBRRR\nBFBBFFFRLL\nBFBBBFBRRR\nFFFFBBFRLR\nFFBBFBFLRR\nFFFFFBBLLR\nBBFBBFBRLL\nFBFBBBBRLR\nBBFFFFBLRL\nFBBFFFBLLR\nFFBFFBBLLL\nFFFBBBFLLR\nFFFBBBFRRR\nFFBBBFBRRR\nFFFBBFFRRR\nFFBBFFBLLR\nBFBFFBFRRR\nFFBFBBFLLR\nBFFFFFFRRR\nFFBFFBFLRL\nBFFBFBBRRR\nFBFBFFFRLL\nBBBFFFBLLL\nBFBBFBFRRL\nBFFFFFBLRR\nFBBBBBFRRR\nFFBBBBFLRR\nBBFBBBBLRR\nBBFBFBFLLR\nFFFFBBFRRR\nFFBBBBBLLR\nBFFFBFBRLR\nFBBBFFBLLL\nFFFFFFFRRR\nFFFBFBFRRL\nBFBBFBBLRR\nFBBBBFBLRL\nFBBBBFBRRR\nBFFFFBFRRR\nBFFBBFFLLL\nFBBFBFBLRL\nBFBBFFFRRL\nFBFBFFBRLR\nFBFFBFFLRR\nBFFFBFBLLR\nBFBBFFBRRR\nBBFBBFBLLL\nBFFBFFFLRR\nFFFBBFFRLL\nBFBBFFFLLL\nBFFFBBBRLL\nFBFFBBFRRR\nFFBFBFBLLR\nFBFFFFBLRR\nFFBBFFFLLL\nFFFBBBBRRL\nBBFBFFFLLL\nBBFFBBFLLR\nBFBFBBBRRR\nFBBBBFBRRL\nFBFFFBFLLR\nFBFBBBFRRR\nBFFFBFBRRL\nFBFBBBFLRL\nBBFFBFFLRL\nBBFBBFFLLR\nFFFFBFFRLL\nFFFBBBBLRL\nFBBBFBFRLL\nBBFFFBBLRL\nFFFBFFBLRR\nBBFBFBBRRL\nFFFFBBBRRR\nFFBBBBBLRL\nFFFFFFBLLL\nFBFFFFFRRL\nFFFFFBBLRR\nBFFFBBBRRL\nFBBFFFFLRL\nFFFFFBBRLR\nFFBFFBFRLL\nFFFBBBFRRL\nBFBBBFFLRL\nFFFFFBFLRR\nBFBFBBBRLR\nFBFBBBFLLL\nBFBFFBFLRL\nFFBFBFFRRR\nFFBBFFFRLL\nBFBFBFFLLL\nFBFBFBBRLR\nBFFBBBFRRL\nFBFFBBBRRR\nFBFBFBBLRR\nBFBBBBFLLR\nFFFBFFFRLR\nBFBBFFBRRL\nBFFFBFFLRL\nBFBFBBFRRR\nFBBFFBFLLL\nFFFFFFBLRR\nFBFFBFBLRR\nFFBBBFFLRR\nFBBBFFBRLL\nBFFFBBBRRR\nFFBFFFFRLL\nBBFFFBFRRR\nBFFBFBBLLL\nBFBBFFBRLR\nFFBFBBBLRR\nFFFBFBBLLL\nFFFBBFFLLL\nFBBBBBBLRL\nBFBFBBBLLL\nBFBFFFFRRL\nFFBFBBFRRR\nFFBFBFBRRL\nFFFBBBBRLL\nBFFBFFBRLL\nBBFFFFBRRL\nFFBFBFBLLL\nFFBFBFBRLL\nFBFBBBFRRL\nFBFFBBFRLR\nBBBFFFFLRL\nFBFBFFFRRL\nFFFBFBFRLR\nFBFBFBBRRL\nBFBBFBBLLL\nFFBBBBBRLL\nBBFFBFBRRL\nFFFBFFFRRR\nFBBFBFBLLL\nBFFFBFFRLR\nFBFBFFBRLL\nBBFBBFFLLL\nFBBBBFFLRR\nFFBBBFFLRL\nFBBBFFBRRR\nFFBBFBBRLR\nFBFBBFFLLR\nBFBBBFFLLR\nFFFBBFFLRR\nFBFFBFFLRL\nBFBFBFFLRR\nBBFBFFFLLR\nFFFBBBBLLR\nFFBBFFBRLL\nBBBFFFBRLL\nFBFFBFBRRL\nBFBFFFFRLL\nFBFBFBFRLR\nBBFFFFFLLL\nFFBFBBBLLR\nFFBFBFFLRR\nFBBBBFBRLR\nFFBFBBBRLR\nBFFBBBBLRL\nFFBBBBBRLR\nBFBBBFFRRR\nFBFBBFBRLL\nFFBFFFBRRL\nBBFBFBFLLL\nBFBBBFBRLR\nBFBBFBFLLR\nFBBFBFFRLL\nFFBFBBFLRR\nBFFBFBFRLL\nFFBBFBBLRL\nFBFBFBBLRL\nBBFFFBFLLR\nBFBFBBBLRR\nBBFFBBBLLR\nBBFFFFBRRR\nBFFFFFBLRL\nFBBBFBBRRR\nBFBFFFBLLL\nFFFBBFFLLR\nBFFBBFFLLR\nBBFBBBBLRL\nFBBFBFFLRR\nFBFBFFBLLR\nBFFFFFFLLL\nBFFBBFFRLL\nBBFFFFFLLR\nFBFFBBFRRL\nFBBFFFFLLR\nBFBFFBBRRL\nFFBFFFBLLL\nBFFFFFBLLR\nFFBBBFBRRL\nFFBBBBFLLR\nBFBFFFBLLR\nFFFFBFFRLR\nBFBBFFBRLL\nFFBBBBBLLL\nFBBFBFFRRR\nBFFFFFFLLR\nFFBBBBBLRR\nFFFFFBFRRR\nBFFFBBBLLL\nBFFFBFFRRR\nFFBBBFBRLR\nBFFBBBBLRR\nBFBBBFFRRL\nBFBFBFFRRR\nBFBBFBBRLR\nBFBBBBFRLL\nFFBBBBFLLL\nFFFBBFBLRR\nFBBFBBFRLR\nBBFBBFFLRR\nFBBFBBBRRL\nBFFBFFFRRL\nBFFFFBFLRR\nFFBFBBFLLL\nFFBFBBBLLL\nFBFFBFBRRR\nFFFBFFBRLL\nBFFFFBFLRL\nFFFFBFFLLR\nBBFBBBBRLL\nFBFBBFBRRR\nBFFFBBBLRR\nFBFFFBFRLL\nFFBBBFBLRL\nFBFFFBBLRR\nFFBBFBFRLR\nFBBBBBFLRL\nFFFFBFBLRR\nBFBFBFBLRR\nFFBBFFFLRL\nBFFBBBFLLR\nFFFFFFBRLR\nFFBBBFBLRR\nFBFBBFFRLL\nBBFBFBFRLR\nFBBFFFFLLL\nBFBBFBFRRR\nBFFBBBFRRR\nFBFFFBFLRR\nFBBFFBFLRL\nBFBBFFFLRR\nFFBFFFFLRL\nBFFBFFBLLL\nFFFBFBBRRR\nBBFFBFFLRR\nBBBFFFFRRL\nFBBBFFBLRL\nFBBFFBBLRR\nFFBFBFFLLR\nFFFBBFFRLR\nFBBBFBBRLR\nFFFFBBBLRR\nBBFFBFBRRR\nFBFBBFFLRL\nFBBBBFFLLL\nFFBFFBBRLR\nBBFFFFFLRR\nFFBFBFBRLR\nFFBFBFBLRL\nFBBBFBBLRL\nFFFBFBBLRL\nFBFBFFFRRR\nBFFBFFFRLR\nBFBBFFBLLR\nBFBFFBFRLL\nFBFBFBFRRR\nFBFFFFBRLL\nFFFFFBBRRR\nFBBBFFFLRL\nFFFBFFBRLR\nBFBFFBFLRR\nFBBFBBFRRL\nBFBBBBFRRR\nBFFFFBBLRR\nFBFFFFFLLL\nBFBFFFBRRL\nFFFBFFBLRL\nFFBFFFBLRR\nFBBFFBFRLL\nBBFBFFBLLL\nBBFFBBFLLL\nFFBBBFFRLL\nBFBBFFFLRL\nFBBFBFFLLR\nFBFBFFBLLL\nFFBBBFFLLR\nFBBFFBFLRR\nFBBFBBFRRR\nBFFFFBBLLL\nFFFBFFBLLR\nFBFBFFFRLR\nFBFBFBBRRR\nFBFBBFBRRL\nBBFBBFBRRR\nFFFFBBBRLL\nFBFFBBBLRL\nBBBFFFFRLL\nFBFFFBFLRL\nBFFFFBFLLR\nFBFBBFFRRL\nBFFBFBBLRR\nFBFBBBBRRL\nFBFBFBBLLR\nFBFFBBFLRR\nFFFFBFFLLL\nBFBFFFFRRR\nBBFFBBBLRR\nFBFFFFFLLR\nBBFBFFFRLR\nBFFFFBBRLR\nFBFFFFFLRL\nFBBBFBBLRR\nBFFBBFBLLL\nBFFBFBBLRL\nBFFBBBFRLL\nFFBFFBFRRR\nBFBFBFBRLL\nBBFBBFBLLR\nFBFBBFBLRL\nFBFFFBBRLR\nBBFBFFBRLL\nBBFFFBFRLR\nFBBFFFBLLL\nBBFBBBBLLL\nBFFFFFFLRR\nFBBBBBFRLL\nBFFFBFBRRR\nBFFFFFFLRL\nFBBBBFBLRR\nFBFFBBBRLR\nFFBBFBFRRL\nFFBBFBBRRL\nFFFBFBFRRR\nFFBBBBFLRL\nBFBBFFFRRR\nFBFBBBBRLL\nFBFFBBFRLL\nFFBFFFFRRR\nBFFFFBBLLR\nFBFBBFBLLR\nBBFFBBBRRR\nFBBFBBBRLR\nBFBFBFFRLL\nBFFBBFBLRL\nBFFBFFFRRR\nFFBBBFBRLL\nFBFFBFFRRL\nFBBBBFFRRR\nFFFBBBFRLL\nBBFFFBBRLL\nBBFFFBBRLR\nFFBBFFFRRL\nBBFFBFBLRR\nBBFBFFBRRR\nBFBBBBBLRR\nBFFBBFFLRL\nBBFFFFBLLL\nFFFFBFBRRL\nFBBFFBBRRR\nFBBBFFFLRR\nFBBFBBFLRR\nFBBBFBBLLL\nFFFFBBFLRL\nFFFFFBBLLL\nBFBBBBBLLR\nBFBFFFFLRR\nFBFFFFBLLR\nBBFFBBBRLL\nFBFFBFFRRR\nFFBBFBFLLR\nBBFBBBFLRR\nFBBBBBBRLL\nFFFFFFBLLR\nFFFFFBFRLR\nFBFFBFBRLL\nBBFFBFFRRR\nBFFBFFFLLR\nFFBBFBBLRR\nBBFFBBBRLR\nFFBBFFBRRL\nFBBBBFFRRL\nBFBFFFFRLR\nBFBBBFBLLL\nBFBFFFBRRR\nFBBBFFFRLR\nBFBBFFBLRR\nBBFBBFFRLR\nBBFFFBBRRR\nFFFFBBBRRL\nFFBFBBFRLL\nFBFFFFBRRL\nFBBBFFBRLR\nFFBFFFBRRR\nFBBBBBBLLL\nBFFBFFBLRL\nFBFFBBBRLL\nBBFBBBFRLR\nBFBFBFBRLR\nBBFFFFBRLL\nFFBBFBBLLR\nFFBBFFBRLR\nBBFBBBBRLR\nBFBBBFBLLR\nFFFFBFFRRR\nBBFFFBFRRL\nFBBFBBBLLL\nFFFBFFFLRL\nBFFFFBBRRR\nFFFBFBFLRL\nBBFFBBFRRR\nFBBFFFFLRR\nFFFBBBFLRL\nBFFBBBFLLL\nBFBBFFBLLL\nFFFFFFBLRL\nFBFFBFFLLL\nFBBBBBBRRR\nFBBFFBBRLR\nBFFFBBBLLR\nBBFBBBBRRR\nBFBFBFFLLR\nBFBFFBFRLR\nFBBBFFFRRR\nFFBFBBFRLR\nFFFFFBFRLL\nFFBFBBBRRR\nBFBFFBBLLL\nFBBBBBFRLR\nFFBBFBBLLL\nBFBFFBBLRL\nFBBFBFBRRL\nBFFBBBBRRL\nFBBFFFBLRL\nFBBFBFBLLR\nFBBFBBBLRR\nBFBBBFBRRL\nFBBBFBFLLL\nBFFFBFFLLR\nFBBBFBFLRR\nFFBFFBBLRL\nBBFBBBBLLR\nBFFFBFFLLL\nFBFFFFFLRR\nBBFBFBBLRL\nBFBFBBFRRL\nFBFBFFBLRR\nBFFFFFFRRL\nBFFFFBFRLR\nBFBBFBBRLL\nBBFFFFFRLL\nFFBBFFFLLR\nFFFBFFFLRR\nFFFBFFBRRR\nBBFBFFBLLR\nBFFBFFFRLL\nFBFBFFBRRL\nBFBBBFFLLL\nBBFFBFBLRL\nFBFBBFFLRR\nFBBFBBBRRR\nFFFBBFBRLL\nFBBFBFBRRR\nBFFFBBFLLL\nFBBBFFBLRR\nBFBFFBBRRR\nFFFFFFBRLL\nBBFFFBFLRL\nBFBFBFBRRR\nBFFFBBFRLR\nBFBFFFBLRR\nFFFBFFBRRL\nBBFFFBBRRL\nBFBBBFBRLL\nBFBFFFBLRL\nFFFBFFFLLR\nBFFBFFFLRL\nBBFBBFBLRR\nFBBBFBBRRL\nFBBFBFFRLR\nFBFFFFFRLR\nFBBBBFFRLR\nBFBFBBFRLL\nBBFBFBFRRR\nBFBFBFBRRL\nFBBBBBBRLR\nBFBFBBFLLR\nBFFFBBFRRL\nBBBFFFFRLR\nBBBFFFBLLR\nFBFBBBFLRR\nFBFFFBBLRL\nFBFFBBBLLR\nBFBFBBFLRR\nBFBBFBBLRL\nBFFFFFBRRL\nFFBBFFFRLR\nBFFBBFFRLR\nBFBFBFBLRL\nBFFBFBFRLR\nFFBBFFBRRR\nBFBBBBBLLL\nBBFFFFFRRL\nBBFFFFFLRL\nFFFBBFFLRL\nBFBBFBFRLL\nFFFBBBBLLL\nFFFFFBFLRL\nFFFFBBFLRR\nFBFFFBFRRR\nBFFBBBBLLL\nBBFBBFFRRL\nBFFFBBFLLR\nFBBBFFFLLL\nFFBFFBBRRL\nBFBBBFBLRR\nBFFBBBFLRL\nBFBBBBBRLL\nFFFBBBFRLR\nFFFFBFFRRL\nFFBFBFFLLL\nBBFBFFFLRL\nBFFFBBFLRR\nFFFBFBFRLL\nBFBFFBBLRR\nFFFBFBBLLR\nBBFFFFFRLR\nFFBFBFFRRL\nFFFFFBBLRL\nFBBBFBFRRL\nFBBBBFBLLL\nFFFFBBBRLR\nFBBBBFFLRL\nBFBBBBBRRL\nBBFFBFBLLR\nFBFBFFFLRL\nFBFFFBFRRL\nFFFBBFBLRL\nBFFFFFBLLL\nBFFBFBFLLL\nFFFFBBFRRL\nFFFBFBBRLR\nFBFBBBBRRR\nFBFFBBBLLL\nFFBBBBFRRR\nBFFFFBFRLL\nBBFBFBBRLR\nBFFBBBFLRR\nFBBFBFFRRL\nFFFFFBFLLL\nBBFBFBFLRR\nFFBFBBFLRL\nBFFBBFBRLR\nFFBBBFFRLR\nFFFBBFBRLR\nFBFBBBBLLR\nBFFBBBBLLR\nBBFBFBFLRL\nBBFFFFFRRR\nFFFBFFFRRL\nFBBFFBFRRR\nBBFFBFFRLL\nFFBBFBFRLL\nFFFFBFBLLR\nBBFFBBFRLL\nBFBBBBFLRL\nFBFFBFFRLR\nBFBFBBFLLL\nFFFFBBFLLL\nBFBBBBBLRL\nFFBFBFBLRR\nBFFFFFBRRR\nFBFBBBBLRL\nFBBFBBFLLR\nFBBFFFFRRL\nFBFFFBFLLL\nFBFFBBBRRL\nFFBFFFFRLR\nFBBFBBBRLL\nFFFFBFBRLR\nFFBFBBBRRL\nBFFBFBFRRL\nFFBFFBFLLL\nBFFBFBFLRR\nBBFBFFBLRL\nBBFFBFFLLR\nBFBBBBFLLL\nBBFBBFFRRR\nBBFFFBBLRR\nBFBFFBFRRL\nFBBFBFBLRR\nBBFBBBFRRR\nFFFBBFBLLR\nFFFBFFFLLL\nFBBBFBFLLR\nBFBBFBFLLL\nBFBFBFBLLL\nBBFFBBFLRR\nFFFBFBFLRR\nBFFFFFFRLR\nBBFBFBBRRR\nBBFFFBFRLL\nFFFFBBFRLL\nFBBFBBFRLL\nFBFFFFBRRR\nFBFFBBFLLR\nBFFBFFBLLR\nFFBFFBFLRR\nFBFFBFBRLR\nFBFBBFFLLL\nFBBFFFBRRL\nFBFBFBFRRL\nFFBFBFBRRR\nFBFBFBFLRL\nFFFBFBBRLL\nFBBBFFFLLR\nFFBBBBFRLL\nFBFFFBBRLL\nBFFBFFBLRR\nFBBFBBFLRL\nFBFFFBBRRR\nFBFFFBBLLR\nBFFBFFBRRR\nFBBBFBFRRR\nFBFFFFFRLL\nBBFBBBFRLL\nFFFBFFBLLL\nFFBFFFFLRR\nFBFFFBBRRL\nBBFFBFFRLR\nFBFBFBBLLL\nFBBBBBBLLR\nFBFBBFBLLL\nBBFBFFFLRR\nBFFFFBBRRL\nBBFFFBFLRR\nFFBFFFBRLL\nFFFFBBBLRL\nBFBBBFFRLL\nBBFBFFFRLL\nFBFBBBBLLL\nBBFBBFBRLR\nBBFFBFBRLR\nBFBFFFFLRL\nFBBBFBFRLR\nFFBFFFBRLR\nFBBBBBFLLR\nFFBBBFBLLR\nBFFBBFBRRL\nBBFFBFFRRL\nFFFFFFBRRR\nFFBBFBBRRR\nFBBBBBBRRL\nBFFBBFFRRL\nFBBFBFBRLR\nFBBFFFFRLL\nFBBBBBFLLL\nFBBFFFBRRR\nBFFFFBBLRL\nFFFFBFBLLL\nFBFBFFFLLL\nFBFBBFBLRR\nFFFFBFFLRR\nFFFBBBFLRR\nFBFFBFFLLR\nBBFFBFFLLL\nFFBFFBFRRL\nBFBBFBBRRR\nBBFFFBFLLL\nFBFFBFBLLL\nBFFBFFBRRL\nBBFBFFBLRR\nFBFBFFFLRR\nBFBBFBBLLR\nBFFBBFFRRR\nFFFFFFBRRL\nBBBFFFFLLR\nBFBFFBFLLL\nFBBBBBFRRL\nBFFBBBBRLR\nFFBBFBFLRL\nFBFBFFBLRL\nFFBBBBFRLR\nBBFBBFBRRL\nFFFFFBFLLR\nFBFBFBFLLL\nBFBFBFBLLR\nFFFBFFFRLL\nBFFBBFBLLR\nFFBBFBBRLL\nFFFBBFBRRL\nFBBFFBBLLL\nFFFBBBBRLR\nFFFBBFBRRR\nBBFFBBBRRL\nFBBFBFFLRL\nFBBBBBFLRR\nBBFBFFBRRL\nFFFBFBFLLL\nFBBBFFFRLL\nBFFBFBFLLR\nFFBBBBBRRL\nBFFBBFFLRR\nFBBFBFBRLL\nBFFFBFFRRL\nBBFFFFBLLR\nBBFFBBFRLR\nBFFFBBFRRR\nFBFBBFBRLR\nFFFFFBBRLL\nFBBFFFBRLL\nBFFFFFBRLL\nBFFFBFBLRR\nBFFBFFBRLR\nFFFFBFBLRL\nFFBFFBFLLR\nFBBFBFFLLL\nBFFBFBFRRR\nBBFBBBFLRL\nBBBFFFFLRR\nBFBBFFFLLR\nFBBFFFBRLR\nFFFFFBFRRL\nFFFBFBBRRL\nBBBFFFBLRR\nFFBFBBFRRL\nFFBBFFBLRR\nBBFFBBBLLL\nBFBFBBBRRL\nBFFFBFBRLL\nFFBFBBBRLL\nFBFBFBFLRR\nFBFFFBBLLL\nFBBFFBFLLR\nBFFFFBFRRL\nFFBBBFFRRL\nFFBFBFFLRL\nBBFBBBFLLR\nFBBFFBFRLR\nFBBFFBBRLL\nBFBFFFBRLR\nBFFFBFFRLL\nBBFBFBBRLL\nBFFFFFFRLL\nFBFBBBFRLL\nBFBBFBFLRR\nBFBFBBBRLL\nBBFBBBFRRL\nBFFBBFBRRR\nBFBFFBFLLR\nFBFBFBFLLR\nFFFFFBBRRL\nFBFBBBFRLR\nFBFFBBFLLL\nFFBFBFFRLR\nBBFBFBBLLL\nFFFFBFFLRL\nFBBFBBFLLL\nBFBFBBFLRL\nFFFFBBFLLR\nBFBBFBBRRL\nFBBBFFBRRL\nFBBBBFFRLL"
}
